### ISSUE TITLE
remove mainBackup.js

### ISSUE THREAD

**Issue by bedrock-adam** [Scoutski/mystery#5]
Anything you commit in git can always be retrieved later if you need it.

Leaving out of date comments and files around creates confusion.

If you need to get back to it, commit the removal as one and then use `git revert [sha]`` or`git checkout -- path/to/file``` to get it back

**Comment by Scoutski** [comment]
Easy enough, I only had that around when I was trying to screw around using a few additional firebase tools and wasn't comfortable enough with branches yet, cheers
