### ISSUE TITLE
move firebase.js into vendor/firebase.js

### ISSUE THREAD

**Issue by bedrock-adam** [Scoutski/mystery#8]
Good practice to separate application library code from vendor (external) code.

Also avoid using the minified version in your source, distribution tools like the ones in HTML5Boilerplate (which you should check out) will minify this automatically when you need to move it to production.

Keeping the non-minified version around will make debugging significantly easier when things go wrong.

**Comment by Scoutski** [comment]
Just confirming that you're talking about these two lines re: minified:

  <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js'></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

What about it will be easier for debugging? I wouldn't need to really touch their code would I?

**Comment by bedrock-adam** [comment]
Say, for example, you accidentally passed the wrong javascript type to a firebase API method, which then blows up.

If the vendor code is minified you often loose a lot of information like their function names, variables within etc to give you a better idea of what may be going wrong.

Always a good idea to write your source code for humans and then use tools to build minified distributions.
